### ISSUE TITLE
the hico-det python API is not working

### ISSUE THREAD

**Issue by monacv** [yeliudev/ConsNet#1]
Hi could you please make this accessible?

https://consnet.readthedocs.io/en/latest/data.html
![Screenshot from 2021-04-08 00-46-44](https://user-images.githubusercontent.com/76495162/113969960-f5bc1500-9803-11eb-8b5b-d836369cf0c4.png)
![Screenshot from 2021-04-08 00-46-35](https://user-images.githubusercontent.com/76495162/113969961-f5bc1500-9803-11eb-8a9d-3b100d935e8a.png)

**Comment by yeliudev** [comment]
Thanks for reporting. The old URL is somehow wrong and I've fixed it. Please try the new one [here](https://consnet.readthedocs.io/en/latest/consnet.api.data.html).
