### ISSUE TITLE
build_mlp

### ISSUE THREAD

**Issue by WXLL579** [yeliudev/ConsNet#11]
hi, my nncore is 0.2.4, but 
  File "/dev/shm/L/ConsNet/consnet/models/blocks/fusion.py", line 9, in <module>
    from nncore.nn import build_mlp
ImportError: cannot import name 'build_mlp' from 'nncore.nn' (/dev/shm/L/ConsNet/nncore/nncore/nn/__init__.py)

hoping for your reply~

**Comment by yeliudev** [comment]
Hi @WXLL579! Could you please double-check whether the version of nncore is exactly 0.2.4? You may try to re-install it using `pip install --force-reinstall nncore==0.2.4`.

**Comment by WXLL579** [comment]
yes. 0.2.4

**Comment by yeliudev** [comment]
It's quite weird, cause I can not reproduce this bug in my environment. And the method `build_mlp` is already imported [here](https://github.com/yeliudev/nncore/blob/0.2.4/nncore/nn/__init__.py#L10).

**Comment by WXLL579** [comment]
it has solved, thanks~!
