### ISSUE TITLE
Lists of unseen objects and unseen actions

### ISSUE THREAD

**Issue by fangruizhu** [yeliudev/ConsNet#12]
Hi,

Thanks for the excellent work. I wonder if you could release the lists of unseen objects and actions you used in the paper or where I could find them.

Thanks!

**Comment by yeliudev** [comment]
Hi @fangruizhu! Thanks for your interest in our work.

The lists of unseen objects and actions can be found [here](https://github.com/yeliudev/ConsNet/blob/main/consnet/api/static.py#L155:L173), where `UO_HOI_IDX` and `UA_HOI_IDX` are HOI ids (0~599) that containing unseen objects and actions, respectively.

**Comment by fangruizhu** [comment]
Got it. Thanks!
