### ISSUE TITLE
regarding config file - build.py

### ISSUE THREAD

**Issue by PradKalkar** [yeliudev/ConsNet#14]
```
build = dict(
    train=dict(
        max_per_img=dict(hum=-1, obj=-1),
        score_thr=dict(hum=0.1, obj=0.1),
        iou_thr=dict(pos=0.6, neg=0.4),
        max_h_as_o=-1,
        neg_pos_ub=50),
    test=dict(
        max_per_img=dict(hum=10, obj=20),
        score_thr=dict(hum=0.5, obj=0.1),
        iou_thr=dict(pos=0.5, neg=0.5),
        max_h_as_o=3))
```

Hi. In this snippet from ```configs/build.py```, would you please explain why are different hyperparameter values used in train and test? (for eg. score thr for hum is 0.1 in train and 0.5 in test). What advantage is achieved by doing so?

Also, what does ```neg_pos_ub``` mean in train?

**Comment by yeliudev** [comment]
Using a lower threshold during training will provide more training samples. And `neg_pos_ub` means the number of negative samples assigned for one positive sample.
