### ISSUE TITLE
feature extraction for bounding boxes - a minor confusion

### ISSUE THREAD

**Issue by PradKalkar** [yeliudev/ConsNet#15]
Hi. Thanks for the great documentation on the README. 

I went through your code for extracting bounding box features through RoIAlign. But, I am still confused. Lets say we already have bounding boxes in our hand which we got from faster-rcnn. Now, I would like to understand the process for a given single bounding box - what is the sequence of layers a given bounding box goes through inorder to arrive at the final 1024 dimensional feature vector for it? Would you please help me with the sequence of layers responsible for feature extraction process?

**Comment by yeliudev** [comment]
Hi @PradKalkar. Sorry for the late reply.

Given a bounding box, the feature extraction process will go through the backbone - FPN - ROIAlign, and the first linear layer in the head.
