### ISSUE TITLE
consistency_graph.pkl

### ISSUE THREAD

**Issue by JingyuLi-code** [yeliudev/ConsNet#16]
When we run python tools/build_dataset.py, we get this error. Do you have any ideas? 

![image](https://github.com/yeliudev/ConsNet/assets/45377489/d5907d4c-e6c5-4ccc-be31-014eadbbf030)

**Comment by yeliudev** [comment]
Hi @JingyuLi-code, may I know your current environment, e.g., Python & CUDA & PyTorch versions?

**Comment by JingyuLi-code** [comment]
We have python=3.9 torch=1.12.1+cu113  mmcv=1.6.0 mmdet=2.24.0

**Comment by yeliudev** [comment]
I think the mmdet version might be too new. Please strictly follow the environment in README and try again.
