### ISSUE TITLE
does ConsNet API visualize the bouding boxes?

### ISSUE THREAD

**Issue by monacv** [yeliudev/ConsNet#4]
Does you API visualize BB? How can I visualize these bounding boxes for the image img_name = 'data/hico_20160224_det/images/test2015/HICO_test2015_00007935.jpg' I have 4 bounding boxes for this image

print(anno[anno[:, 0] == img_id])
yields:
tensor([[7935.,  133.,  566.,  128.,  594.,  190.,  533.,  159.,  628.,  217.],
        [7935.,  133.,  349.,  108.,  425.,  233.,  233.,  134.,  484.,  354.],
        [7935.,  139.,  563.,  126.,  602.,  207.,  519.,  154.,  635.,  260.],
        [7935.,  139.,  334.,   98.,  421.,  241.,  222.,  127.,  484.,  350.]])

**Comment by monacv** [comment]
looking for a method better than this that can capture visualization of HOI pairs

bb = anno[anno[:, 0] == img_id]
image = cv2.imread(img_name)
for i, box in enumerate(bb):
    cv2.rectangle(image, (int(box[2]), int(box[3])), (int(box[4]), int(box[5])), (255, 153, 255), 3)
    cv2.imshow("output", image)

**Comment by yeliudev** [comment]
Thanks for your suggestion, but I'm afraid that we do not provide visualization methods in the current version. Will consider implementing it in the next release.

**Comment by monacv** [comment]
thank you. do you know how I can visualize the bounding box around the objects?
from consnet.api import load_anno
import cv2
from random import randint

img_name = 'data/hico_20160224_det/images/train2015/HICO_train2015_00037321.jpg'
img_id = int(img_name[-12:-4])

if cv2.waitKey(1):
    cv2.destroyAllWindows()

anno = load_anno('data/hico_20160224_det/anno_bbox.mat', 'train')
bb = anno[anno[:, 0] == img_id]
image = cv2.imread(img_name)
print(bb[0])
print(type(bb[0]))
print("len bb ", len(bb))
for i, box in enumerate(bb):
    print(" {} and {}".format(i, box))
    cv2.rectangle(image, (int(box[2]), int(box[3])), (int(box[4]), int(box[5])),
                 (randint(0, 255), randint(0, 255),  randint(0, 255)), 3)
    cv2.imshow("output", image)
cv2.waitKey(100000)
cv2.destroyAllWindows()


I get these bounding boxes:
<class 'torch.Tensor'>
```
len bb  2
 0 and tensor([37321.,   268.,   211.,    50.,   438.,   425.,   251.,   344.,   359.,
          397.])
 1 and tensor([37321.,   271.,   206.,    47.,   442.,   427.,   249.,   342.,   362.,
          400.])
```
it shows two bounding boxes both of which around the girl with green shit
![Screenshot from 2021-04-09 16-28-25](https://user-images.githubusercontent.com/76495162/114237164-adf6d400-9950-11eb-8170-2c8e25de13d4.png)

**Comment by yeliudev** [comment]
Here

```
cv2.rectangle(image, (int(box[2]), int(box[3])), (int(box[4]), int(box[5])), (randint(0, 255), randint(0, 255), randint(0, 255)), 3)
```

draws the bbox of the human. You may also draw the bbox of the object using

```
cv2.rectangle(image, (int(box[3]), int(box[6])), (int(box[8]), int(box[9])), (randint(0, 255), randint(0, 255), randint(0, 255)), 3)
```
