### ISSUE TITLE
build_dataset.py

### ISSUE THREAD

**Issue by WXLL579** [yeliudev/ConsNet#5]
Thanks for you work! I got an error:

(conse) LSX@csm:/disk1/LSX/ConsNet$ python tools/build_dataset.py
/disk1/LSX/ConsNet/mmdetection/mmdet/core/anchor/builder.py:15: UserWarning: ``build_anchor_generator`` would be deprecated soon, please use ``build_prior_generator``
  warnings.warn(
/disk1/LSX/ConsNet/mmdetection/mmdet/datasets/api_wrappers/coco_api.py:19: UserWarning: mmpycocotools is deprecated. Please install official pycocotools by "pip install pycocotools"
  warnings.warn(
loading annotations into memory...
Done (t=0.82s)
creating index...
index created!
detecting objects in *train* split
[                                        ] 0/37633, 0.0 task/s, elapsed: 0s, ETA: 0sTraceback (most recent call last):
  File "/disk1/LSX/ConsNet/tools/build_dataset.py", line 288, in <module>
    main()
  File "/disk1/LSX/ConsNet/tools/build_dataset.py", line 278, in main
    blobs[split] = detect_objects(model, data_loader, annos, split)
  File "/disk1/LSX/ConsNet/tools/build_dataset.py", line 37, in detect_objects
    gt_blobs, dt_blobs = model(return_loss=False, **data)
  File "/home/LSX/anaconda3/envs/conse/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/LSX/anaconda3/envs/conse/lib/python3.9/site-packages/mmcv/parallel/data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/LSX/anaconda3/envs/conse/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/LSX/anaconda3/envs/conse/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/LSX/anaconda3/envs/conse/lib/python3.9/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/disk1/LSX/ConsNet/mmdetection/mmdet/models/detectors/base.py", line 173, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/disk1/LSX/ConsNet/mmdetection/mmdet/models/detectors/base.py", line 146, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/disk1/LSX/ConsNet/consnet/models/detectors/hooked_rcnn.py", line 29, in simple_test
    gt_blobs, _ = self.roi_head.simple_test(
  File "/disk1/LSX/ConsNet/consnet/models/detectors/hooked_roi_head.py", line 20, in simple_test
    return self.simple_test_bboxes(
  File "/disk1/LSX/ConsNet/mmdetection/mmdet/models/roi_heads/test_mixins.py", line 126, in simple_test_bboxes
    det_bbox, det_label = self.bbox_head.get_bboxes(
  File "/disk1/LSX/ConsNet/consnet/models/detectors/hooked_bbox_head.py", line 70, in get_bboxes
    gt_blob, dt_blob = _hooked_nms(*blob, feat, **cfg)
  File "/disk1/LSX/ConsNet/consnet/models/detectors/hooked_bbox_head.py", line 17, in _hooked_nms
    scores = scores[:, :-1]
IndexError: too many indices for tensor of dimension 1

**Comment by yeliudev** [comment]
Hi @WXLL579! May I ask that which version of mmdet are you using? As restricted in `setup.py`, this repo works with `allennlp>=2.2,<2.3`, `mmcv-full>=1.3,<1.4` and `mmdet>=2.11,<2.12`.

**Comment by WXLL579** [comment]
thanks,I have checked the version, now it is mmdet==2.11.0,mmcv-full==1.3.9, allennlp==2.2.0
but  another error appears:

  File "/disk1/LSX/ConsNet/tools/build_dataset.py", line 287, in <module>
    main()
  File "/disk1/LSX/ConsNet/tools/build_dataset.py", line 277, in main
    blobs[split] = detect_objects(model, data_loader, annos, split)
  File "/disk1/LSX/ConsNet/tools/build_dataset.py", line 36, in detect_objects
    gt_blobs, dt_blobs = model(return_loss=False, **data)
  File "/home/LSX/anaconda3/envs/con/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/LSX/anaconda3/envs/con/lib/python3.9/site-packages/mmcv/parallel/data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/LSX/anaconda3/envs/con/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/LSX/anaconda3/envs/con/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/LSX/anaconda3/envs/con/lib/python3.9/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/LSX/anaconda3/envs/con/lib/python3.9/site-packages/mmdet/models/detectors/base.py", line 183, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/LSX/anaconda3/envs/con/lib/python3.9/site-packages/mmdet/models/detectors/base.py", line 160, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/disk1/LSX/ConsNet/consnet/models/detectors/hooked_rcnn.py", line 29, in simple_test
    gt_blobs, _ = self.roi_head.simple_test(
  File "/disk1/LSX/ConsNet/consnet/models/detectors/hooked_roi_head.py", line 20, in simple_test
    return self.simple_test_bboxes(
  File "/home/LSX/anaconda3/envs/con/lib/python3.9/site-packages/mmdet/models/roi_heads/test_mixins.py", line 157, in simple_test_bboxes
    return self.bbox_head.get_bboxes(
  File "/disk1/LSX/ConsNet/consnet/models/detectors/hooked_bbox_head.py", line 68, in get_bboxes
    gt_blob, dt_blob = _hooked_nms(*blob, feat, **cfg)
  File "/disk1/LSX/ConsNet/consnet/models/detectors/hooked_bbox_head.py", line 42, in _hooked_nms
    dets, keep = batched_nms(bboxes, scores, labels, nms)
  File "/home/LSX/anaconda3/envs/con/lib/python3.9/site-packages/mmcv/ops/nms.py", line 307, in batched_nms
    dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
  File "/home/LSX/anaconda3/envs/con/lib/python3.9/site-packages/mmcv/utils/misc.py", line 330, in new_func
    output = old_func(*args, **kwargs)
  File "/home/LSX/anaconda3/envs/con/lib/python3.9/site-packages/mmcv/ops/nms.py", line 171, in nms
    inds = NMSop.apply(boxes, scores, iou_threshold, offset,
  File "/home/LSX/anaconda3/envs/con/lib/python3.9/site-packages/mmcv/ops/nms.py", line 26, in forward
    inds = ext_module.nms(
RuntimeError: nms is not compiled with GPU support

under the nvcc -V ,I found that Cuda compilation tools, release 7.5,
but I have successfully installed torh1.8.1 and torchvision0.9.1, do you konw what happened?

Thanks!!

**Comment by WXLL579** [comment]
and also this error :
File "/disk1/LSX/ConsNet/consnet/models/detectors/hooked_bbox_head.py", line 17, in _hooked_nms
scores = scores[:, :-1]
IndexError: too many indices for tensor of dimension 1

**Comment by yeliudev** [comment]
It seems that your mmcv-full is not compiled correctly (see [here](https://mmcv.readthedocs.io/en/latest/faq.html)). Could you please also check 1) whether the GPU version of PyTorch is installed, and 2) whether the cuda ops are compiled when installing mmcv-full? Simply running `pip install mmcv-full==1.3.9` may not compile the cuda ops automatically when your cuda environment is not configured correctly.

**Comment by yeliudev** [comment]
> and also this error :
> File "/disk1/LSX/ConsNet/consnet/models/detectors/hooked_bbox_head.py", line 17, in _hooked_nms
> scores = scores[:, :-1]
> IndexError: too many indices for tensor of dimension 1

I've double check the mmdet version. `2.14.0` raises this error but `2.11.0` works fine.

**Comment by WXLL579** [comment]
This is my configuration, and also this error :
File "/disk1/LSX/ConsNet/consnet/models/detectors/hooked_bbox_head.py", line 17, in _hooked_nms
scores = scores[:, :-1]
IndexError: too many indices for tensor of dimension 1


(t18py39) ➜  ConsNet git:(main) pip list
Package            Version             Location
------------------ ------------------- --------------------------
addict             2.4.0
allennlp           2.2.0
attrs              21.2.0
blis               0.7.4
boto3              1.18.13
botocore           1.21.13
catalogue          2.0.4
certifi            2021.5.30
charset-normalizer 2.0.4
click              7.1.2
configparser       5.0.2
consnet            1.0.5
cycler             0.10.0
cymem              2.0.5
Cython             0.29.24
docker-pycreds     0.4.0
filelock           3.0.12
gitdb              4.0.7
GitPython          3.1.20
h5py               3.3.0
idna               3.2
iniconfig          1.1.1
install            1.3.4
Jinja2             3.0.1
jmespath           0.10.0
joblib             1.0.1
jsonnet            0.17.0
jsonpickle         2.0.0
kiwisolver         1.3.1
lmdb               1.2.1
MarkupSafe         2.0.1
matplotlib         3.4.2
mmcv-full          1.3.9
mmdet              2.11.0              /dev/shm/w/LLL/mmdetection
more-itertools     8.8.0
murmurhash         1.0.5
nltk               3.6.2
nncore             0.2.4
numpy              1.21.1
opencv-python      4.5.3.56
overrides          3.1.0
packaging          21.0
pathtools          0.1.2
pathy              0.6.0
Pillow             8.3.1
pip                21.2.2
pluggy             0.13.1
preshed            3.0.5
promise            2.3
protobuf           3.17.3
psutil             5.8.0
py                 1.10.0
pycocotools        2.0.2
pydantic           1.8.2
pynvml             11.0.0
pyparsing          2.4.7
pytest             6.2.4
python-dateutil    2.8.2
PyYAML             5.4.1
regex              2021.8.3
requests           2.26.0
s3transfer         0.5.0
sacremoses         0.0.45
scikit-learn       0.24.2
scipy              1.7.1
sentencepiece      0.1.96
sentry-sdk         1.3.1
setuptools         49.6.0.post20210108
shortuuid          1.0.1
six                1.16.0
smart-open         5.1.0
smmap              4.0.0
spacy              3.0.7
spacy-legacy       3.0.8
srsly              2.4.1
subprocess32       3.5.4
tabulate           0.8.9
tensorboardX       2.4
termcolor          1.1.0
terminaltables     3.1.0
thinc              8.0.8
threadpoolctl      2.2.0
tokenizers         0.10.3
toml               0.10.2
torch              1.8.1+cu101
torchvision        0.9.1+cu101
tqdm               4.62.0
transformers       4.4.2
typer              0.3.2
typing-extensions  3.10.0.0
upsample-ext       0.0.1
urllib3            1.26.6
wandb              0.10.33
wasabi             0.8.2
wheel              0.36.2
yapf               0.31.0

**Comment by yeliudev** [comment]
Your configuration seems fine, could you please also check whether the imported mmdet points to the correct version?
```python
from mmdet import __version__
print(__version__)
```
I also notice that before this error, two warnings are raised in your case. But these warnings do not exist in `2.11.0`.
```
UserWarning: build_anchor_generator would be deprecated soon, please use build_prior_generator
UserWarning: mmpycocotools is deprecated. Please install official pycocotools by "pip install pycocotools"
```
Here's the environment configuration script we use to reproduce the results. You may have a try by re-creating the conda env from scratch. Currently, I have no idea why the error still exists given the information you've provided.
```
conda create -n consnet python=3.9 -y
conda activate consnet

pip install torch==1.8.1 torchvision

cd <path-to-repo>
pip install -e .[full]
```
Also, here's the configuration we use for your reference.
```
Package                  Version   Location
------------------------ --------- -----------------------------------------------
addict                   2.4.0
allennlp                 2.2.0
argon2-cffi              20.1.0
async-generator          1.10
attrs                    21.2.0
backcall                 0.2.0
backports.csv            1.0.7
beautifulsoup4           4.9.3
bleach                   3.3.1
blis                     0.7.4
boto3                    1.18.12
botocore                 1.21.12
cachetools               4.2.2
catalogue                2.0.4
certifi                  2021.5.30
cffi                     1.14.6
chardet                  4.0.0
charset-normalizer       2.0.4
checklist                0.0.11
cheroot                  8.5.2
CherryPy                 18.6.1
click                    7.1.2
configparser             5.0.2
consnet                  1.0.5     /cfs/cfs-417f0454c/17f0454c/imyeliu/ConsNet
cryptography             3.4.7
cycler                   0.10.0
cymem                    2.0.5
Cython                   0.29.24
debugpy                  1.4.1
decorator                5.0.9
defusedxml               0.7.1
dill                     0.3.4
docker-pycreds           0.4.0
entrypoints              0.3
feedparser               6.0.8
filelock                 3.0.12
flake8                   3.9.2
future                   0.18.2
gitdb                    4.0.7
GitPython                3.1.20
google-api-core          1.31.1
google-auth              1.34.0
google-cloud-core        1.7.2
google-cloud-storage     1.41.1
google-crc32c            1.1.2
google-resumable-media   1.3.3
googleapis-common-protos 1.53.0
h5py                     3.3.0
huggingface-hub          0.0.12
idna                     3.2
iniconfig                1.1.1
ipykernel                6.0.3
ipython                  7.26.0
ipython-genutils         0.2.0
ipywidgets               7.6.3
iso-639                  0.4.5
isort                    5.9.3
jaraco.classes           3.2.1
jaraco.collections       3.3.0
jaraco.functools         3.3.0
jaraco.text              3.5.1
jedi                     0.18.0
Jinja2                   3.0.1
jmespath                 0.10.0
joblib                   1.0.1
jsonnet                  0.17.0
jsonpickle               2.0.0
jsonschema               3.2.0
jupyter                  1.0.0
jupyter-client           6.2.0
jupyter-console          6.4.0
jupyter-core             4.7.1
jupyterlab-pygments      0.1.2
jupyterlab-widgets       1.0.0
kiwisolver               1.3.1
lmdb                     1.2.1
lxml                     4.6.3
MarkupSafe               2.0.1
matplotlib               3.4.2
matplotlib-inline        0.1.2
mccabe                   0.6.1
mistune                  0.8.4
mmcv-full                1.3.9
mmdet                    2.11.0
mmpycocotools            12.0.3
more-itertools           8.8.0
munch                    2.5.0
murmurhash               1.0.5
nbclient                 0.5.3
nbconvert                6.1.0
nbformat                 5.1.3
nest-asyncio             1.5.1
nltk                     3.6.2
nncore                   0.2.6
notebook                 6.4.0
numpy                    1.21.1
opencv-python            4.5.3.56
overrides                3.1.0
packaging                21.0
pandocfilters            1.4.3
parso                    0.8.2
pathtools                0.1.2
pathy                    0.6.0
patternfork-nosql        3.6
pdfminer.six             20201018
pexpect                  4.8.0
pickleshare              0.7.5
Pillow                   8.3.1
pip                      21.2.2
pip-review               1.1.0
pluggy                   0.13.1
portend                  2.7.1
preshed                  3.0.5
prometheus-client        0.11.0
promise                  2.3
prompt-toolkit           3.0.19
protobuf                 3.17.3
psutil                   5.8.0
ptyprocess               0.7.0
py                       1.10.0
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pycocotools              2.0.2
pycodestyle              2.7.0
pycparser                2.20
pydantic                 1.8.2
pyflakes                 2.3.1
Pygments                 2.9.0
pyparsing                2.4.7
pyrsistent               0.18.0
pytest                   6.2.4
python-dateutil          2.8.2
python-docx              0.8.11
pytz                     2021.1
PyYAML                   5.4.1
pyzmq                    22.1.0
qtconsole                5.1.1
QtPy                     1.9.0
regex                    2021.7.6
requests                 2.26.0
rsa                      4.7.2
s3transfer               0.5.0
sacremoses               0.0.45
scikit-learn             0.24.2
scipy                    1.7.1
Send2Trash               1.7.1
sentencepiece            0.1.96
sentry-sdk               1.3.1
setuptools               57.4.0
sgmllib3k                1.0.0
shortuuid                1.0.1
six                      1.16.0
smart-open               5.1.0
smmap                    4.0.0
sortedcontainers         2.4.0
soupsieve                2.2.1
spacy                    3.0.7
spacy-legacy             3.0.8
srsly                    2.4.1
subprocess32             3.5.4
tabulate                 0.8.9
tempora                  4.1.1
tensorboardX             2.4
termcolor                1.1.0
terminado                0.10.1
terminaltables           3.1.0
testpath                 0.5.0
thinc                    8.0.8
threadpoolctl            2.2.0
tokenizers               0.10.3
toml                     0.10.2
torch                    1.8.1
torchvision              0.9.1
tornado                  6.1
tqdm                     4.62.0
traitlets                5.0.5
transformers             4.4.2
typer                    0.3.2
typing-extensions        3.10.0.0
urllib3                  1.26.6
wandb                    0.10.33
wasabi                   0.8.2
wcwidth                  0.2.5
webencodings             0.5.1
wheel                    0.36.2
widgetsnbextension       3.5.1
yapf                     0.31.0
zc.lockfile              2.0
```

**Comment by WXLL579** [comment]
sorry, I also have another question on how to build mmcv-full. If i use pip to install mmcv-full, then cuda will be not available on mmcv-full, like this,
(ConsNet) ➜  w python
Python 3.9.2 (default, Mar  3 2021, 20:02:32)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mmcv.ops import get_compiling_cuda_version, get_compiler_version
>>> print(get_compiling_cuda_version())
not available
>>> exit()

but if i want to build it from source , i cannot find the whl of mmcv-full for cu101 torch1.8.1, do you have some ideas about how to build mmcv-full ? thanks!

**Comment by yeliudev** [comment]
You may try installing mmcv-full with cu101 and torch1.8.0 at [here](https://download.openmmlab.com/mmcv/dist/cu101/torch1.8.0/index.html), but I'm not sure whether it also supports torch1.8.1.

**Comment by WXLL579** [comment]
ok thanks for your reply~

**Comment by Dawn-LX** [comment]
The function `get_bboxes` has changed in the new version of mmdet.
my version: `mmdet v2.25.2`, and `mmcv-full v1.6.2`. I modified the function `get_bboxes` and it works
I modified the function at https://github.com/yeliudev/ConsNet/blob/e0d7c1a455ec126498ee41bd3fd918d82569acc8/consnet/models/detectors/hooked_bbox_head.py#L61
```
    def get_bboxes(self, *args, **kwargs):
        cfg = kwargs.pop('cfg')

        blobs = super(HookedBBoxHead, self).get_bboxes(*args, **kwargs)  # we use  mmdet v2.25.2
        '''
        ###############NOTE version change NOTE: BBoxHead.get_bboxes
        in mmdet v2.11 (which is used by the original ConsNet):
            func:`get_bboxes` returns:
                tuple[list[Tensor], list[Tensor]] or tuple[Tensor, Tensor]:
                If the input has a batch dimension, the return value is
                a tuple of the list. The first list contains the boxes of
                the corresponding image in a batch, each tensor has the
                shape (num_boxes, 5) and last dimension 5 represent
                (tl_x, tl_y, br_x, br_y, score). Each Tensor in the second
                list is the labels with shape (num_boxes, ). The length of
                both lists should be equal to batch_size. Otherwise return
                value is a tuple of two tensors, the first tensor is the
                boxes with scores, the second tensor is the labels, both
                have the same shape as the first case.

        in mmdet v2.25.2 refer to in "mmdet/models/roi_heads/bbox_heads/bbox_head.py"
            func:`get_bboxes` is only process one image, and it returns:
                tuple[Tensor, Tensor]:
                First tensor is `det_bboxes`, has the shape
                (num_boxes, 5) and last
                dimension 5 represent (tl_x, tl_y, br_x, br_y, score).
                Second tensor is the labels with shape (num_boxes, ). 
            refer to  func:`simple_test_bboxes` in "mmdet/models/roi_heads/test_mixins.py"
            NOTE `simple_test_bboxes` calls `get_bboxes` for each img individually
            
        '''
        (
            rois,       # (num_boxes,5)  format:[batch_index, x1, y1, x2, y2]
            cls_score,  # (num_boxes,81) 81 == num_classes + 1  
            bbox_pred,  # (num_boxes,320) 320 == 4*80
            img_shape,  # tuple: (H,W,3)
            scale_factor # list: [w_scale, h_scale, w_scale, h_scale]
        ) = args

        # num_rois, gt_blobs, dt_blobs = blobs[0][0].size(0), [], []  # this is not compatible with mmdet v2.25.2
        
        bboxes,scores = blobs
        num_boxes = bboxes.size(0)  # num_rois == num_boxes
        
        # self._feat.shape == (num_boxes,1024); 
        assert self._feat.shape[0] == num_boxes ## actually there is only one img per_gpu in ConsNet's implementation
        
        gt_blob, dt_blob = _hooked_nms(bboxes,scores,self._feat, **cfg)


        return gt_blob, dt_blob

```
