### ISSUE TITLE
Could not download the checkpoint files

### ISSUE THREAD

**Issue by RawFisher** [yeliudev/ConsNet#7]
Hi. Thanks for your excellent work!
I wait for long time when I execute `wget https://catcatserver.xyz/models/faster_rcnn_r50_fpn_3x_coco-26df6f6b.pth`.
Is that address work? Or could you provide the URL that can be used in China?

**Comment by yeliudev** [comment]
@RawFisher Thanks for your interest! The server has been fixed. You may try it again.

**Comment by hannajiang** [comment]
Hi. Thanks for your excellent work! I also can't download .pth when I execute wget https://catcatserver.xyz/models/faster_rcnn_r50_fpn_3x_coco-26df6f6b.pth; Can you give another link?

**Comment by yeliudev** [comment]
Hi @hannajiang, you may try to use `https://www4.comp.polyu.edu.hk/~csyeliu/dl/consnet/<filename>` to download all the checkpoint or metric files in this repo, where `<filename>` is the name of the file.
